In [6]:
import pandas as pd
from sqlalchemy import create_engine, text
import os
from dotenv import load_dotenv

In [3]:
load_dotenv()

True

In [4]:
engine = create_engine(f"mysql+mysqlconnector://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@"
    f"{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}",
    echo=True)

In [ ]:
'''
files = ['questionsxtags.sql', 'answersxtags.sql', 'tagsxyear.sql', 'tagxtime.sql']
for file in files:
    with engine.connect() as conn:
        with open(f'{file}',"r", encoding="utf-8") as f:
            sql = f.read()
        conn.execute(text(sql))
        conn.commit()
'''

In [31]:
df = pd.read_csv('csv_analises/questionsxtags.csv', names = ['tag','quantity'])

In [32]:
df

                  tag  quantity
0                   t       872
1                   r       868
2                   c       748
3            learning       453
4    machine-learning       359
..                ...       ...
126            matrix         6
127    language-model         6
128       mathematics         6
129           seaborn         6
130          lightgbm         6

[131 rows x 2 columns]

In [29]:
df1

                  tag  quantity
0                   t       872
1                   r       868
2                   c       748
3            learning       453
4    machine-learning       359
..                ...       ...
81      preprocessing        11
82           gradient        11
83                gbm        11
84           training        11
85  model-evaluations        11

[86 rows x 2 columns]